// flow-typed signature: f6c7bdd1028d497fb61efef1a6a93b9a
// flow-typed version: <<STUB>>/pretty-quick_v^2.0.1/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pretty-quick'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pretty-quick' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pretty-quick/bin/pretty-quick' {
  declare module.exports: any;
}

declare module 'pretty-quick/dist/__tests__/pretty-quick.test' {
  declare module.exports: any;
}

declare module 'pretty-quick/dist/__tests__/scm-git.test' {
  declare module.exports: any;
}

declare module 'pretty-quick/dist/__tests__/scm-hg.test' {
  declare module.exports: any;
}

declare module 'pretty-quick/dist/createIgnorer' {
  declare module.exports: any;
}

declare module 'pretty-quick/dist/createMatcher' {
  declare module.exports: any;
}

declare module 'pretty-quick/dist' {
  declare module.exports: any;
}

declare module 'pretty-quick/dist/isSupportedExtension' {
  declare module.exports: any;
}

declare module 'pretty-quick/dist/processFiles' {
  declare module.exports: any;
}

declare module 'pretty-quick/dist/scms/git' {
  declare module.exports: any;
}

declare module 'pretty-quick/dist/scms/hg' {
  declare module.exports: any;
}

declare module 'pretty-quick/dist/scms' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pretty-quick/bin/pretty-quick.js' {
  declare module.exports: $Exports<'pretty-quick/bin/pretty-quick'>;
}
declare module 'pretty-quick/dist/__tests__/pretty-quick.test.js' {
  declare module.exports: $Exports<'pretty-quick/dist/__tests__/pretty-quick.test'>;
}
declare module 'pretty-quick/dist/__tests__/scm-git.test.js' {
  declare module.exports: $Exports<'pretty-quick/dist/__tests__/scm-git.test'>;
}
declare module 'pretty-quick/dist/__tests__/scm-hg.test.js' {
  declare module.exports: $Exports<'pretty-quick/dist/__tests__/scm-hg.test'>;
}
declare module 'pretty-quick/dist/createIgnorer.js' {
  declare module.exports: $Exports<'pretty-quick/dist/createIgnorer'>;
}
declare module 'pretty-quick/dist/createMatcher.js' {
  declare module.exports: $Exports<'pretty-quick/dist/createMatcher'>;
}
declare module 'pretty-quick/dist/index' {
  declare module.exports: $Exports<'pretty-quick/dist'>;
}
declare module 'pretty-quick/dist/index.js' {
  declare module.exports: $Exports<'pretty-quick/dist'>;
}
declare module 'pretty-quick/dist/isSupportedExtension.js' {
  declare module.exports: $Exports<'pretty-quick/dist/isSupportedExtension'>;
}
declare module 'pretty-quick/dist/processFiles.js' {
  declare module.exports: $Exports<'pretty-quick/dist/processFiles'>;
}
declare module 'pretty-quick/dist/scms/git.js' {
  declare module.exports: $Exports<'pretty-quick/dist/scms/git'>;
}
declare module 'pretty-quick/dist/scms/hg.js' {
  declare module.exports: $Exports<'pretty-quick/dist/scms/hg'>;
}
declare module 'pretty-quick/dist/scms/index' {
  declare module.exports: $Exports<'pretty-quick/dist/scms'>;
}
declare module 'pretty-quick/dist/scms/index.js' {
  declare module.exports: $Exports<'pretty-quick/dist/scms'>;
}
