// flow-typed signature: 161f88e357c51e79c0eccaa262237c2e
// flow-typed version: <<STUB>>/react-native-localize_v^1.4.0/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-localize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-localize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-localize/lib/commonjs/constants' {
  declare module.exports: any;
}

declare module 'react-native-localize/lib/commonjs' {
  declare module.exports: any;
}

declare module 'react-native-localize/lib/commonjs/module' {
  declare module.exports: any;
}

declare module 'react-native-localize/lib/commonjs/module.web' {
  declare module.exports: any;
}

declare module 'react-native-localize/lib/commonjs/types' {
  declare module.exports: any;
}

declare module 'react-native-localize/lib/module/constants' {
  declare module.exports: any;
}

declare module 'react-native-localize/lib/module' {
  declare module.exports: any;
}

declare module 'react-native-localize/lib/module/module' {
  declare module.exports: any;
}

declare module 'react-native-localize/lib/module/module.web' {
  declare module.exports: any;
}

declare module 'react-native-localize/lib/module/types' {
  declare module.exports: any;
}

declare module 'react-native-localize/src/constants' {
  declare module.exports: any;
}

declare module 'react-native-localize/src' {
  declare module.exports: any;
}

declare module 'react-native-localize/src/module' {
  declare module.exports: any;
}

declare module 'react-native-localize/src/module.web' {
  declare module.exports: any;
}

declare module 'react-native-localize/src/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-localize/lib/commonjs/constants.js' {
  declare module.exports: $Exports<'react-native-localize/lib/commonjs/constants'>;
}
declare module 'react-native-localize/lib/commonjs/index' {
  declare module.exports: $Exports<'react-native-localize/lib/commonjs'>;
}
declare module 'react-native-localize/lib/commonjs/index.js' {
  declare module.exports: $Exports<'react-native-localize/lib/commonjs'>;
}
declare module 'react-native-localize/lib/commonjs/module.js' {
  declare module.exports: $Exports<'react-native-localize/lib/commonjs/module'>;
}
declare module 'react-native-localize/lib/commonjs/module.web.js' {
  declare module.exports: $Exports<'react-native-localize/lib/commonjs/module.web'>;
}
declare module 'react-native-localize/lib/commonjs/types.js' {
  declare module.exports: $Exports<'react-native-localize/lib/commonjs/types'>;
}
declare module 'react-native-localize/lib/module/constants.js' {
  declare module.exports: $Exports<'react-native-localize/lib/module/constants'>;
}
declare module 'react-native-localize/lib/module/index' {
  declare module.exports: $Exports<'react-native-localize/lib/module'>;
}
declare module 'react-native-localize/lib/module/index.js' {
  declare module.exports: $Exports<'react-native-localize/lib/module'>;
}
declare module 'react-native-localize/lib/module/module.js' {
  declare module.exports: $Exports<'react-native-localize/lib/module/module'>;
}
declare module 'react-native-localize/lib/module/module.web.js' {
  declare module.exports: $Exports<'react-native-localize/lib/module/module.web'>;
}
declare module 'react-native-localize/lib/module/types.js' {
  declare module.exports: $Exports<'react-native-localize/lib/module/types'>;
}
declare module 'react-native-localize/src/constants.js' {
  declare module.exports: $Exports<'react-native-localize/src/constants'>;
}
declare module 'react-native-localize/src/index' {
  declare module.exports: $Exports<'react-native-localize/src'>;
}
declare module 'react-native-localize/src/index.js' {
  declare module.exports: $Exports<'react-native-localize/src'>;
}
declare module 'react-native-localize/src/module.js' {
  declare module.exports: $Exports<'react-native-localize/src/module'>;
}
declare module 'react-native-localize/src/module.web.js' {
  declare module.exports: $Exports<'react-native-localize/src/module.web'>;
}
declare module 'react-native-localize/src/types.js' {
  declare module.exports: $Exports<'react-native-localize/src/types'>;
}
