// flow-typed signature: 8176686bf0e963cb5970983a93fac753
// flow-typed version: <<STUB>>/react-native-typography_v^1.4.1/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-typography'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-typography' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-typography/dist/collections/human' {
  declare module.exports: any;
}

declare module 'react-native-typography/dist/collections/humanDense' {
  declare module.exports: any;
}

declare module 'react-native-typography/dist/collections/humanTall' {
  declare module.exports: any;
}

declare module 'react-native-typography/dist/collections/iOSUIKit' {
  declare module.exports: any;
}

declare module 'react-native-typography/dist/collections/iOSUIKitDense' {
  declare module.exports: any;
}

declare module 'react-native-typography/dist/collections/iOSUIKitTall' {
  declare module.exports: any;
}

declare module 'react-native-typography/dist/collections/material' {
  declare module.exports: any;
}

declare module 'react-native-typography/dist/collections/materialDense' {
  declare module.exports: any;
}

declare module 'react-native-typography/dist/collections/materialTall' {
  declare module.exports: any;
}

declare module 'react-native-typography/dist/helpers/iOSColors' {
  declare module.exports: any;
}

declare module 'react-native-typography/dist/helpers/materialColors' {
  declare module.exports: any;
}

declare module 'react-native-typography/dist/helpers/notoCJKWeights' {
  declare module.exports: any;
}

declare module 'react-native-typography/dist/helpers/notoTallWeights' {
  declare module.exports: any;
}

declare module 'react-native-typography/dist/helpers/robotoWeights' {
  declare module.exports: any;
}

declare module 'react-native-typography/dist/helpers/sanFranciscoSpacing' {
  declare module.exports: any;
}

declare module 'react-native-typography/dist/helpers/sanFranciscoWeights' {
  declare module.exports: any;
}

declare module 'react-native-typography/dist/helpers/systemDenseWeights.android' {
  declare module.exports: any;
}

declare module 'react-native-typography/dist/helpers/systemDenseWeights.ios' {
  declare module.exports: any;
}

declare module 'react-native-typography/dist/helpers/systemDenseWeights.web' {
  declare module.exports: any;
}

declare module 'react-native-typography/dist/helpers/systemTallWeights.android' {
  declare module.exports: any;
}

declare module 'react-native-typography/dist/helpers/systemTallWeights.ios' {
  declare module.exports: any;
}

declare module 'react-native-typography/dist/helpers/systemTallWeights.web' {
  declare module.exports: any;
}

declare module 'react-native-typography/dist/helpers/systemWeights.android' {
  declare module.exports: any;
}

declare module 'react-native-typography/dist/helpers/systemWeights.ios' {
  declare module.exports: any;
}

declare module 'react-native-typography/dist/helpers/systemWeights.web' {
  declare module.exports: any;
}

declare module 'react-native-typography/dist/helpers/webWeights' {
  declare module.exports: any;
}

declare module 'react-native-typography/dist' {
  declare module.exports: any;
}

declare module 'react-native-typography/dist/internal/CombinedStyleSheet' {
  declare module.exports: any;
}

declare module 'react-native-typography/dist/internal/suffixProperties' {
  declare module.exports: any;
}

declare module 'react-native-typography/src/collections/human' {
  declare module.exports: any;
}

declare module 'react-native-typography/src/collections/humanDense' {
  declare module.exports: any;
}

declare module 'react-native-typography/src/collections/humanTall' {
  declare module.exports: any;
}

declare module 'react-native-typography/src/collections/iOSUIKit' {
  declare module.exports: any;
}

declare module 'react-native-typography/src/collections/iOSUIKitDense' {
  declare module.exports: any;
}

declare module 'react-native-typography/src/collections/iOSUIKitTall' {
  declare module.exports: any;
}

declare module 'react-native-typography/src/collections/material' {
  declare module.exports: any;
}

declare module 'react-native-typography/src/collections/materialDense' {
  declare module.exports: any;
}

declare module 'react-native-typography/src/collections/materialTall' {
  declare module.exports: any;
}

declare module 'react-native-typography/src/helpers/iOSColors' {
  declare module.exports: any;
}

declare module 'react-native-typography/src/helpers/materialColors' {
  declare module.exports: any;
}

declare module 'react-native-typography/src/helpers/notoCJKWeights' {
  declare module.exports: any;
}

declare module 'react-native-typography/src/helpers/notoTallWeights' {
  declare module.exports: any;
}

declare module 'react-native-typography/src/helpers/robotoWeights' {
  declare module.exports: any;
}

declare module 'react-native-typography/src/helpers/sanFranciscoSpacing' {
  declare module.exports: any;
}

declare module 'react-native-typography/src/helpers/sanFranciscoWeights' {
  declare module.exports: any;
}

declare module 'react-native-typography/src/helpers/systemDenseWeights.android' {
  declare module.exports: any;
}

declare module 'react-native-typography/src/helpers/systemDenseWeights.ios' {
  declare module.exports: any;
}

declare module 'react-native-typography/src/helpers/systemDenseWeights.web' {
  declare module.exports: any;
}

declare module 'react-native-typography/src/helpers/systemTallWeights.android' {
  declare module.exports: any;
}

declare module 'react-native-typography/src/helpers/systemTallWeights.ios' {
  declare module.exports: any;
}

declare module 'react-native-typography/src/helpers/systemTallWeights.web' {
  declare module.exports: any;
}

declare module 'react-native-typography/src/helpers/systemWeights.android' {
  declare module.exports: any;
}

declare module 'react-native-typography/src/helpers/systemWeights.ios' {
  declare module.exports: any;
}

declare module 'react-native-typography/src/helpers/systemWeights.web' {
  declare module.exports: any;
}

declare module 'react-native-typography/src/helpers/webWeights' {
  declare module.exports: any;
}

declare module 'react-native-typography/src' {
  declare module.exports: any;
}

declare module 'react-native-typography/src/internal/CombinedStyleSheet' {
  declare module.exports: any;
}

declare module 'react-native-typography/src/internal/suffixProperties' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-typography/dist/collections/human.js' {
  declare module.exports: $Exports<'react-native-typography/dist/collections/human'>;
}
declare module 'react-native-typography/dist/collections/humanDense.js' {
  declare module.exports: $Exports<'react-native-typography/dist/collections/humanDense'>;
}
declare module 'react-native-typography/dist/collections/humanTall.js' {
  declare module.exports: $Exports<'react-native-typography/dist/collections/humanTall'>;
}
declare module 'react-native-typography/dist/collections/iOSUIKit.js' {
  declare module.exports: $Exports<'react-native-typography/dist/collections/iOSUIKit'>;
}
declare module 'react-native-typography/dist/collections/iOSUIKitDense.js' {
  declare module.exports: $Exports<'react-native-typography/dist/collections/iOSUIKitDense'>;
}
declare module 'react-native-typography/dist/collections/iOSUIKitTall.js' {
  declare module.exports: $Exports<'react-native-typography/dist/collections/iOSUIKitTall'>;
}
declare module 'react-native-typography/dist/collections/material.js' {
  declare module.exports: $Exports<'react-native-typography/dist/collections/material'>;
}
declare module 'react-native-typography/dist/collections/materialDense.js' {
  declare module.exports: $Exports<'react-native-typography/dist/collections/materialDense'>;
}
declare module 'react-native-typography/dist/collections/materialTall.js' {
  declare module.exports: $Exports<'react-native-typography/dist/collections/materialTall'>;
}
declare module 'react-native-typography/dist/helpers/iOSColors.js' {
  declare module.exports: $Exports<'react-native-typography/dist/helpers/iOSColors'>;
}
declare module 'react-native-typography/dist/helpers/materialColors.js' {
  declare module.exports: $Exports<'react-native-typography/dist/helpers/materialColors'>;
}
declare module 'react-native-typography/dist/helpers/notoCJKWeights.js' {
  declare module.exports: $Exports<'react-native-typography/dist/helpers/notoCJKWeights'>;
}
declare module 'react-native-typography/dist/helpers/notoTallWeights.js' {
  declare module.exports: $Exports<'react-native-typography/dist/helpers/notoTallWeights'>;
}
declare module 'react-native-typography/dist/helpers/robotoWeights.js' {
  declare module.exports: $Exports<'react-native-typography/dist/helpers/robotoWeights'>;
}
declare module 'react-native-typography/dist/helpers/sanFranciscoSpacing.js' {
  declare module.exports: $Exports<'react-native-typography/dist/helpers/sanFranciscoSpacing'>;
}
declare module 'react-native-typography/dist/helpers/sanFranciscoWeights.js' {
  declare module.exports: $Exports<'react-native-typography/dist/helpers/sanFranciscoWeights'>;
}
declare module 'react-native-typography/dist/helpers/systemDenseWeights.android.js' {
  declare module.exports: $Exports<'react-native-typography/dist/helpers/systemDenseWeights.android'>;
}
declare module 'react-native-typography/dist/helpers/systemDenseWeights.ios.js' {
  declare module.exports: $Exports<'react-native-typography/dist/helpers/systemDenseWeights.ios'>;
}
declare module 'react-native-typography/dist/helpers/systemDenseWeights.web.js' {
  declare module.exports: $Exports<'react-native-typography/dist/helpers/systemDenseWeights.web'>;
}
declare module 'react-native-typography/dist/helpers/systemTallWeights.android.js' {
  declare module.exports: $Exports<'react-native-typography/dist/helpers/systemTallWeights.android'>;
}
declare module 'react-native-typography/dist/helpers/systemTallWeights.ios.js' {
  declare module.exports: $Exports<'react-native-typography/dist/helpers/systemTallWeights.ios'>;
}
declare module 'react-native-typography/dist/helpers/systemTallWeights.web.js' {
  declare module.exports: $Exports<'react-native-typography/dist/helpers/systemTallWeights.web'>;
}
declare module 'react-native-typography/dist/helpers/systemWeights.android.js' {
  declare module.exports: $Exports<'react-native-typography/dist/helpers/systemWeights.android'>;
}
declare module 'react-native-typography/dist/helpers/systemWeights.ios.js' {
  declare module.exports: $Exports<'react-native-typography/dist/helpers/systemWeights.ios'>;
}
declare module 'react-native-typography/dist/helpers/systemWeights.web.js' {
  declare module.exports: $Exports<'react-native-typography/dist/helpers/systemWeights.web'>;
}
declare module 'react-native-typography/dist/helpers/webWeights.js' {
  declare module.exports: $Exports<'react-native-typography/dist/helpers/webWeights'>;
}
declare module 'react-native-typography/dist/index' {
  declare module.exports: $Exports<'react-native-typography/dist'>;
}
declare module 'react-native-typography/dist/index.js' {
  declare module.exports: $Exports<'react-native-typography/dist'>;
}
declare module 'react-native-typography/dist/internal/CombinedStyleSheet.js' {
  declare module.exports: $Exports<'react-native-typography/dist/internal/CombinedStyleSheet'>;
}
declare module 'react-native-typography/dist/internal/suffixProperties.js' {
  declare module.exports: $Exports<'react-native-typography/dist/internal/suffixProperties'>;
}
declare module 'react-native-typography/src/collections/human.js' {
  declare module.exports: $Exports<'react-native-typography/src/collections/human'>;
}
declare module 'react-native-typography/src/collections/humanDense.js' {
  declare module.exports: $Exports<'react-native-typography/src/collections/humanDense'>;
}
declare module 'react-native-typography/src/collections/humanTall.js' {
  declare module.exports: $Exports<'react-native-typography/src/collections/humanTall'>;
}
declare module 'react-native-typography/src/collections/iOSUIKit.js' {
  declare module.exports: $Exports<'react-native-typography/src/collections/iOSUIKit'>;
}
declare module 'react-native-typography/src/collections/iOSUIKitDense.js' {
  declare module.exports: $Exports<'react-native-typography/src/collections/iOSUIKitDense'>;
}
declare module 'react-native-typography/src/collections/iOSUIKitTall.js' {
  declare module.exports: $Exports<'react-native-typography/src/collections/iOSUIKitTall'>;
}
declare module 'react-native-typography/src/collections/material.js' {
  declare module.exports: $Exports<'react-native-typography/src/collections/material'>;
}
declare module 'react-native-typography/src/collections/materialDense.js' {
  declare module.exports: $Exports<'react-native-typography/src/collections/materialDense'>;
}
declare module 'react-native-typography/src/collections/materialTall.js' {
  declare module.exports: $Exports<'react-native-typography/src/collections/materialTall'>;
}
declare module 'react-native-typography/src/helpers/iOSColors.js' {
  declare module.exports: $Exports<'react-native-typography/src/helpers/iOSColors'>;
}
declare module 'react-native-typography/src/helpers/materialColors.js' {
  declare module.exports: $Exports<'react-native-typography/src/helpers/materialColors'>;
}
declare module 'react-native-typography/src/helpers/notoCJKWeights.js' {
  declare module.exports: $Exports<'react-native-typography/src/helpers/notoCJKWeights'>;
}
declare module 'react-native-typography/src/helpers/notoTallWeights.js' {
  declare module.exports: $Exports<'react-native-typography/src/helpers/notoTallWeights'>;
}
declare module 'react-native-typography/src/helpers/robotoWeights.js' {
  declare module.exports: $Exports<'react-native-typography/src/helpers/robotoWeights'>;
}
declare module 'react-native-typography/src/helpers/sanFranciscoSpacing.js' {
  declare module.exports: $Exports<'react-native-typography/src/helpers/sanFranciscoSpacing'>;
}
declare module 'react-native-typography/src/helpers/sanFranciscoWeights.js' {
  declare module.exports: $Exports<'react-native-typography/src/helpers/sanFranciscoWeights'>;
}
declare module 'react-native-typography/src/helpers/systemDenseWeights.android.js' {
  declare module.exports: $Exports<'react-native-typography/src/helpers/systemDenseWeights.android'>;
}
declare module 'react-native-typography/src/helpers/systemDenseWeights.ios.js' {
  declare module.exports: $Exports<'react-native-typography/src/helpers/systemDenseWeights.ios'>;
}
declare module 'react-native-typography/src/helpers/systemDenseWeights.web.js' {
  declare module.exports: $Exports<'react-native-typography/src/helpers/systemDenseWeights.web'>;
}
declare module 'react-native-typography/src/helpers/systemTallWeights.android.js' {
  declare module.exports: $Exports<'react-native-typography/src/helpers/systemTallWeights.android'>;
}
declare module 'react-native-typography/src/helpers/systemTallWeights.ios.js' {
  declare module.exports: $Exports<'react-native-typography/src/helpers/systemTallWeights.ios'>;
}
declare module 'react-native-typography/src/helpers/systemTallWeights.web.js' {
  declare module.exports: $Exports<'react-native-typography/src/helpers/systemTallWeights.web'>;
}
declare module 'react-native-typography/src/helpers/systemWeights.android.js' {
  declare module.exports: $Exports<'react-native-typography/src/helpers/systemWeights.android'>;
}
declare module 'react-native-typography/src/helpers/systemWeights.ios.js' {
  declare module.exports: $Exports<'react-native-typography/src/helpers/systemWeights.ios'>;
}
declare module 'react-native-typography/src/helpers/systemWeights.web.js' {
  declare module.exports: $Exports<'react-native-typography/src/helpers/systemWeights.web'>;
}
declare module 'react-native-typography/src/helpers/webWeights.js' {
  declare module.exports: $Exports<'react-native-typography/src/helpers/webWeights'>;
}
declare module 'react-native-typography/src/index' {
  declare module.exports: $Exports<'react-native-typography/src'>;
}
declare module 'react-native-typography/src/index.js' {
  declare module.exports: $Exports<'react-native-typography/src'>;
}
declare module 'react-native-typography/src/internal/CombinedStyleSheet.js' {
  declare module.exports: $Exports<'react-native-typography/src/internal/CombinedStyleSheet'>;
}
declare module 'react-native-typography/src/internal/suffixProperties.js' {
  declare module.exports: $Exports<'react-native-typography/src/internal/suffixProperties'>;
}
