// flow-typed signature: 08c8938a63848ab69cbc0caff3e35f5c
// flow-typed version: <<STUB>>/react-native-safe-area-context_v^3.0.2/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-safe-area-context'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-safe-area-context' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-safe-area-context/lib/commonjs' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/commonjs/InitialWindow' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/commonjs/InitialWindow.native' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/commonjs/NativeSafeAreaProvider' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/commonjs/NativeSafeAreaProvider.native' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/commonjs/SafeArea.types' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/commonjs/SafeAreaContext' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/commonjs/SafeAreaView' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/commonjs/SafeAreaView.native' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/module' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/module/InitialWindow' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/module/InitialWindow.native' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/module/NativeSafeAreaProvider' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/module/NativeSafeAreaProvider.native' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/module/SafeArea.types' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/module/SafeAreaContext' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/module/SafeAreaView' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/module/SafeAreaView.native' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-safe-area-context/lib/commonjs/index' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/commonjs'>;
}
declare module 'react-native-safe-area-context/lib/commonjs/index.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/commonjs'>;
}
declare module 'react-native-safe-area-context/lib/commonjs/InitialWindow.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/commonjs/InitialWindow'>;
}
declare module 'react-native-safe-area-context/lib/commonjs/InitialWindow.native.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/commonjs/InitialWindow.native'>;
}
declare module 'react-native-safe-area-context/lib/commonjs/NativeSafeAreaProvider.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/commonjs/NativeSafeAreaProvider'>;
}
declare module 'react-native-safe-area-context/lib/commonjs/NativeSafeAreaProvider.native.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/commonjs/NativeSafeAreaProvider.native'>;
}
declare module 'react-native-safe-area-context/lib/commonjs/SafeArea.types.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/commonjs/SafeArea.types'>;
}
declare module 'react-native-safe-area-context/lib/commonjs/SafeAreaContext.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/commonjs/SafeAreaContext'>;
}
declare module 'react-native-safe-area-context/lib/commonjs/SafeAreaView.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/commonjs/SafeAreaView'>;
}
declare module 'react-native-safe-area-context/lib/commonjs/SafeAreaView.native.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/commonjs/SafeAreaView.native'>;
}
declare module 'react-native-safe-area-context/lib/module/index' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/module'>;
}
declare module 'react-native-safe-area-context/lib/module/index.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/module'>;
}
declare module 'react-native-safe-area-context/lib/module/InitialWindow.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/module/InitialWindow'>;
}
declare module 'react-native-safe-area-context/lib/module/InitialWindow.native.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/module/InitialWindow.native'>;
}
declare module 'react-native-safe-area-context/lib/module/NativeSafeAreaProvider.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/module/NativeSafeAreaProvider'>;
}
declare module 'react-native-safe-area-context/lib/module/NativeSafeAreaProvider.native.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/module/NativeSafeAreaProvider.native'>;
}
declare module 'react-native-safe-area-context/lib/module/SafeArea.types.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/module/SafeArea.types'>;
}
declare module 'react-native-safe-area-context/lib/module/SafeAreaContext.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/module/SafeAreaContext'>;
}
declare module 'react-native-safe-area-context/lib/module/SafeAreaView.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/module/SafeAreaView'>;
}
declare module 'react-native-safe-area-context/lib/module/SafeAreaView.native.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/module/SafeAreaView.native'>;
}
