// flow-typed signature: 0d2d6f4bca65b65ca35505ef9f24a047
// flow-typed version: <<STUB>>/react-native-offline_v^5.6.2/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-offline'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-offline' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-offline/dist/react-native-offline.esm' {
  declare module.exports: any;
}

declare module 'react-native-offline/dist/react-native-offline' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-offline/dist/react-native-offline.esm.js' {
  declare module.exports: $Exports<'react-native-offline/dist/react-native-offline.esm'>;
}
declare module 'react-native-offline/dist/react-native-offline.js' {
  declare module.exports: $Exports<'react-native-offline/dist/react-native-offline'>;
}
