// flow-typed signature: fbd00aa97c784ccfce84615882dbcbb1
// flow-typed version: <<STUB>>/@react-native-community/cli-debugger-ui_v^4.9.0/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@react-native-community/cli-debugger-ui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@react-native-community/cli-debugger-ui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@react-native-community/cli-debugger-ui/build/middleware' {
  declare module.exports: any;
}

declare module '@react-native-community/cli-debugger-ui/build/ui/debuggerWorker.cff11639' {
  declare module.exports: any;
}

declare module '@react-native-community/cli-debugger-ui/build/ui/debuggerWorker' {
  declare module.exports: any;
}

declare module '@react-native-community/cli-debugger-ui/build/ui' {
  declare module.exports: any;
}

declare module '@react-native-community/cli-debugger-ui/build/ui/ui.bcd3f9d1' {
  declare module.exports: any;
}

// Filename aliases
declare module '@react-native-community/cli-debugger-ui/build/middleware/index' {
  declare module.exports: $Exports<'@react-native-community/cli-debugger-ui/build/middleware'>;
}
declare module '@react-native-community/cli-debugger-ui/build/middleware/index.js' {
  declare module.exports: $Exports<'@react-native-community/cli-debugger-ui/build/middleware'>;
}
declare module '@react-native-community/cli-debugger-ui/build/ui/debuggerWorker.cff11639.js' {
  declare module.exports: $Exports<'@react-native-community/cli-debugger-ui/build/ui/debuggerWorker.cff11639'>;
}
declare module '@react-native-community/cli-debugger-ui/build/ui/debuggerWorker.js' {
  declare module.exports: $Exports<'@react-native-community/cli-debugger-ui/build/ui/debuggerWorker'>;
}
declare module '@react-native-community/cli-debugger-ui/build/ui/index' {
  declare module.exports: $Exports<'@react-native-community/cli-debugger-ui/build/ui'>;
}
declare module '@react-native-community/cli-debugger-ui/build/ui/index.js' {
  declare module.exports: $Exports<'@react-native-community/cli-debugger-ui/build/ui'>;
}
declare module '@react-native-community/cli-debugger-ui/build/ui/ui.bcd3f9d1.js' {
  declare module.exports: $Exports<'@react-native-community/cli-debugger-ui/build/ui/ui.bcd3f9d1'>;
}
