// flow-typed signature: d2a072b8f1c039ef3ee999f1ad073248
// flow-typed version: <<STUB>>/@react-navigation/drawer_v^5.8.1/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@react-navigation/drawer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@react-navigation/drawer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@react-navigation/drawer/lib/commonjs' {
  declare module.exports: any;
}

declare module '@react-navigation/drawer/lib/commonjs/navigators/createDrawerNavigator' {
  declare module.exports: any;
}

declare module '@react-navigation/drawer/lib/commonjs/types' {
  declare module.exports: any;
}

declare module '@react-navigation/drawer/lib/commonjs/utils/DrawerGestureContext' {
  declare module.exports: any;
}

declare module '@react-navigation/drawer/lib/commonjs/utils/DrawerOpenContext' {
  declare module.exports: any;
}

declare module '@react-navigation/drawer/lib/commonjs/utils/DrawerPositionContext' {
  declare module.exports: any;
}

declare module '@react-navigation/drawer/lib/commonjs/utils/useIsDrawerOpen' {
  declare module.exports: any;
}

declare module '@react-navigation/drawer/lib/commonjs/views/Drawer' {
  declare module.exports: any;
}

declare module '@react-navigation/drawer/lib/commonjs/views/DrawerContent' {
  declare module.exports: any;
}

declare module '@react-navigation/drawer/lib/commonjs/views/DrawerContentScrollView' {
  declare module.exports: any;
}

declare module '@react-navigation/drawer/lib/commonjs/views/DrawerItem' {
  declare module.exports: any;
}

declare module '@react-navigation/drawer/lib/commonjs/views/DrawerItemList' {
  declare module.exports: any;
}

declare module '@react-navigation/drawer/lib/commonjs/views/DrawerView' {
  declare module.exports: any;
}

declare module '@react-navigation/drawer/lib/commonjs/views/GestureHandler' {
  declare module.exports: any;
}

declare module '@react-navigation/drawer/lib/commonjs/views/GestureHandler.native' {
  declare module.exports: any;
}

declare module '@react-navigation/drawer/lib/commonjs/views/Overlay' {
  declare module.exports: any;
}

declare module '@react-navigation/drawer/lib/commonjs/views/ResourceSavingScene' {
  declare module.exports: any;
}

declare module '@react-navigation/drawer/lib/commonjs/views/SafeAreaProviderCompat' {
  declare module.exports: any;
}

declare module '@react-navigation/drawer/lib/commonjs/views/TouchableItem' {
  declare module.exports: any;
}

declare module '@react-navigation/drawer/lib/module' {
  declare module.exports: any;
}

declare module '@react-navigation/drawer/lib/module/navigators/createDrawerNavigator' {
  declare module.exports: any;
}

declare module '@react-navigation/drawer/lib/module/types' {
  declare module.exports: any;
}

declare module '@react-navigation/drawer/lib/module/utils/DrawerGestureContext' {
  declare module.exports: any;
}

declare module '@react-navigation/drawer/lib/module/utils/DrawerOpenContext' {
  declare module.exports: any;
}

declare module '@react-navigation/drawer/lib/module/utils/DrawerPositionContext' {
  declare module.exports: any;
}

declare module '@react-navigation/drawer/lib/module/utils/useIsDrawerOpen' {
  declare module.exports: any;
}

declare module '@react-navigation/drawer/lib/module/views/Drawer' {
  declare module.exports: any;
}

declare module '@react-navigation/drawer/lib/module/views/DrawerContent' {
  declare module.exports: any;
}

declare module '@react-navigation/drawer/lib/module/views/DrawerContentScrollView' {
  declare module.exports: any;
}

declare module '@react-navigation/drawer/lib/module/views/DrawerItem' {
  declare module.exports: any;
}

declare module '@react-navigation/drawer/lib/module/views/DrawerItemList' {
  declare module.exports: any;
}

declare module '@react-navigation/drawer/lib/module/views/DrawerView' {
  declare module.exports: any;
}

declare module '@react-navigation/drawer/lib/module/views/GestureHandler' {
  declare module.exports: any;
}

declare module '@react-navigation/drawer/lib/module/views/GestureHandler.native' {
  declare module.exports: any;
}

declare module '@react-navigation/drawer/lib/module/views/Overlay' {
  declare module.exports: any;
}

declare module '@react-navigation/drawer/lib/module/views/ResourceSavingScene' {
  declare module.exports: any;
}

declare module '@react-navigation/drawer/lib/module/views/SafeAreaProviderCompat' {
  declare module.exports: any;
}

declare module '@react-navigation/drawer/lib/module/views/TouchableItem' {
  declare module.exports: any;
}

// Filename aliases
declare module '@react-navigation/drawer/lib/commonjs/index' {
  declare module.exports: $Exports<'@react-navigation/drawer/lib/commonjs'>;
}
declare module '@react-navigation/drawer/lib/commonjs/index.js' {
  declare module.exports: $Exports<'@react-navigation/drawer/lib/commonjs'>;
}
declare module '@react-navigation/drawer/lib/commonjs/navigators/createDrawerNavigator.js' {
  declare module.exports: $Exports<'@react-navigation/drawer/lib/commonjs/navigators/createDrawerNavigator'>;
}
declare module '@react-navigation/drawer/lib/commonjs/types.js' {
  declare module.exports: $Exports<'@react-navigation/drawer/lib/commonjs/types'>;
}
declare module '@react-navigation/drawer/lib/commonjs/utils/DrawerGestureContext.js' {
  declare module.exports: $Exports<'@react-navigation/drawer/lib/commonjs/utils/DrawerGestureContext'>;
}
declare module '@react-navigation/drawer/lib/commonjs/utils/DrawerOpenContext.js' {
  declare module.exports: $Exports<'@react-navigation/drawer/lib/commonjs/utils/DrawerOpenContext'>;
}
declare module '@react-navigation/drawer/lib/commonjs/utils/DrawerPositionContext.js' {
  declare module.exports: $Exports<'@react-navigation/drawer/lib/commonjs/utils/DrawerPositionContext'>;
}
declare module '@react-navigation/drawer/lib/commonjs/utils/useIsDrawerOpen.js' {
  declare module.exports: $Exports<'@react-navigation/drawer/lib/commonjs/utils/useIsDrawerOpen'>;
}
declare module '@react-navigation/drawer/lib/commonjs/views/Drawer.js' {
  declare module.exports: $Exports<'@react-navigation/drawer/lib/commonjs/views/Drawer'>;
}
declare module '@react-navigation/drawer/lib/commonjs/views/DrawerContent.js' {
  declare module.exports: $Exports<'@react-navigation/drawer/lib/commonjs/views/DrawerContent'>;
}
declare module '@react-navigation/drawer/lib/commonjs/views/DrawerContentScrollView.js' {
  declare module.exports: $Exports<'@react-navigation/drawer/lib/commonjs/views/DrawerContentScrollView'>;
}
declare module '@react-navigation/drawer/lib/commonjs/views/DrawerItem.js' {
  declare module.exports: $Exports<'@react-navigation/drawer/lib/commonjs/views/DrawerItem'>;
}
declare module '@react-navigation/drawer/lib/commonjs/views/DrawerItemList.js' {
  declare module.exports: $Exports<'@react-navigation/drawer/lib/commonjs/views/DrawerItemList'>;
}
declare module '@react-navigation/drawer/lib/commonjs/views/DrawerView.js' {
  declare module.exports: $Exports<'@react-navigation/drawer/lib/commonjs/views/DrawerView'>;
}
declare module '@react-navigation/drawer/lib/commonjs/views/GestureHandler.js' {
  declare module.exports: $Exports<'@react-navigation/drawer/lib/commonjs/views/GestureHandler'>;
}
declare module '@react-navigation/drawer/lib/commonjs/views/GestureHandler.native.js' {
  declare module.exports: $Exports<'@react-navigation/drawer/lib/commonjs/views/GestureHandler.native'>;
}
declare module '@react-navigation/drawer/lib/commonjs/views/Overlay.js' {
  declare module.exports: $Exports<'@react-navigation/drawer/lib/commonjs/views/Overlay'>;
}
declare module '@react-navigation/drawer/lib/commonjs/views/ResourceSavingScene.js' {
  declare module.exports: $Exports<'@react-navigation/drawer/lib/commonjs/views/ResourceSavingScene'>;
}
declare module '@react-navigation/drawer/lib/commonjs/views/SafeAreaProviderCompat.js' {
  declare module.exports: $Exports<'@react-navigation/drawer/lib/commonjs/views/SafeAreaProviderCompat'>;
}
declare module '@react-navigation/drawer/lib/commonjs/views/TouchableItem.js' {
  declare module.exports: $Exports<'@react-navigation/drawer/lib/commonjs/views/TouchableItem'>;
}
declare module '@react-navigation/drawer/lib/module/index' {
  declare module.exports: $Exports<'@react-navigation/drawer/lib/module'>;
}
declare module '@react-navigation/drawer/lib/module/index.js' {
  declare module.exports: $Exports<'@react-navigation/drawer/lib/module'>;
}
declare module '@react-navigation/drawer/lib/module/navigators/createDrawerNavigator.js' {
  declare module.exports: $Exports<'@react-navigation/drawer/lib/module/navigators/createDrawerNavigator'>;
}
declare module '@react-navigation/drawer/lib/module/types.js' {
  declare module.exports: $Exports<'@react-navigation/drawer/lib/module/types'>;
}
declare module '@react-navigation/drawer/lib/module/utils/DrawerGestureContext.js' {
  declare module.exports: $Exports<'@react-navigation/drawer/lib/module/utils/DrawerGestureContext'>;
}
declare module '@react-navigation/drawer/lib/module/utils/DrawerOpenContext.js' {
  declare module.exports: $Exports<'@react-navigation/drawer/lib/module/utils/DrawerOpenContext'>;
}
declare module '@react-navigation/drawer/lib/module/utils/DrawerPositionContext.js' {
  declare module.exports: $Exports<'@react-navigation/drawer/lib/module/utils/DrawerPositionContext'>;
}
declare module '@react-navigation/drawer/lib/module/utils/useIsDrawerOpen.js' {
  declare module.exports: $Exports<'@react-navigation/drawer/lib/module/utils/useIsDrawerOpen'>;
}
declare module '@react-navigation/drawer/lib/module/views/Drawer.js' {
  declare module.exports: $Exports<'@react-navigation/drawer/lib/module/views/Drawer'>;
}
declare module '@react-navigation/drawer/lib/module/views/DrawerContent.js' {
  declare module.exports: $Exports<'@react-navigation/drawer/lib/module/views/DrawerContent'>;
}
declare module '@react-navigation/drawer/lib/module/views/DrawerContentScrollView.js' {
  declare module.exports: $Exports<'@react-navigation/drawer/lib/module/views/DrawerContentScrollView'>;
}
declare module '@react-navigation/drawer/lib/module/views/DrawerItem.js' {
  declare module.exports: $Exports<'@react-navigation/drawer/lib/module/views/DrawerItem'>;
}
declare module '@react-navigation/drawer/lib/module/views/DrawerItemList.js' {
  declare module.exports: $Exports<'@react-navigation/drawer/lib/module/views/DrawerItemList'>;
}
declare module '@react-navigation/drawer/lib/module/views/DrawerView.js' {
  declare module.exports: $Exports<'@react-navigation/drawer/lib/module/views/DrawerView'>;
}
declare module '@react-navigation/drawer/lib/module/views/GestureHandler.js' {
  declare module.exports: $Exports<'@react-navigation/drawer/lib/module/views/GestureHandler'>;
}
declare module '@react-navigation/drawer/lib/module/views/GestureHandler.native.js' {
  declare module.exports: $Exports<'@react-navigation/drawer/lib/module/views/GestureHandler.native'>;
}
declare module '@react-navigation/drawer/lib/module/views/Overlay.js' {
  declare module.exports: $Exports<'@react-navigation/drawer/lib/module/views/Overlay'>;
}
declare module '@react-navigation/drawer/lib/module/views/ResourceSavingScene.js' {
  declare module.exports: $Exports<'@react-navigation/drawer/lib/module/views/ResourceSavingScene'>;
}
declare module '@react-navigation/drawer/lib/module/views/SafeAreaProviderCompat.js' {
  declare module.exports: $Exports<'@react-navigation/drawer/lib/module/views/SafeAreaProviderCompat'>;
}
declare module '@react-navigation/drawer/lib/module/views/TouchableItem.js' {
  declare module.exports: $Exports<'@react-navigation/drawer/lib/module/views/TouchableItem'>;
}
