// flow-typed signature: 0e1037fe3c2d49c76fd199a298a7593e
// flow-typed version: <<STUB>>/@react-navigation/native_v^5.5.0/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@react-navigation/native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@react-navigation/native' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@react-navigation/native/lib/commonjs' {
  declare module.exports: any;
}

declare module '@react-navigation/native/lib/commonjs/Link' {
  declare module.exports: any;
}

declare module '@react-navigation/native/lib/commonjs/LinkingContext' {
  declare module.exports: any;
}

declare module '@react-navigation/native/lib/commonjs/NavigationContainer' {
  declare module.exports: any;
}

declare module '@react-navigation/native/lib/commonjs/ServerContainer' {
  declare module.exports: any;
}

declare module '@react-navigation/native/lib/commonjs/ServerContext' {
  declare module.exports: any;
}

declare module '@react-navigation/native/lib/commonjs/theming/DarkTheme' {
  declare module.exports: any;
}

declare module '@react-navigation/native/lib/commonjs/theming/DefaultTheme' {
  declare module.exports: any;
}

declare module '@react-navigation/native/lib/commonjs/theming/ThemeContext' {
  declare module.exports: any;
}

declare module '@react-navigation/native/lib/commonjs/theming/ThemeProvider' {
  declare module.exports: any;
}

declare module '@react-navigation/native/lib/commonjs/theming/useTheme' {
  declare module.exports: any;
}

declare module '@react-navigation/native/lib/commonjs/types' {
  declare module.exports: any;
}

declare module '@react-navigation/native/lib/commonjs/useBackButton' {
  declare module.exports: any;
}

declare module '@react-navigation/native/lib/commonjs/useLinkBuilder' {
  declare module.exports: any;
}

declare module '@react-navigation/native/lib/commonjs/useLinking' {
  declare module.exports: any;
}

declare module '@react-navigation/native/lib/commonjs/useLinking.native' {
  declare module.exports: any;
}

declare module '@react-navigation/native/lib/commonjs/useLinkProps' {
  declare module.exports: any;
}

declare module '@react-navigation/native/lib/commonjs/useLinkTo' {
  declare module.exports: any;
}

declare module '@react-navigation/native/lib/commonjs/useScrollToTop' {
  declare module.exports: any;
}

declare module '@react-navigation/native/lib/commonjs/useThenable' {
  declare module.exports: any;
}

declare module '@react-navigation/native/lib/module' {
  declare module.exports: any;
}

declare module '@react-navigation/native/lib/module/Link' {
  declare module.exports: any;
}

declare module '@react-navigation/native/lib/module/LinkingContext' {
  declare module.exports: any;
}

declare module '@react-navigation/native/lib/module/NavigationContainer' {
  declare module.exports: any;
}

declare module '@react-navigation/native/lib/module/ServerContainer' {
  declare module.exports: any;
}

declare module '@react-navigation/native/lib/module/ServerContext' {
  declare module.exports: any;
}

declare module '@react-navigation/native/lib/module/theming/DarkTheme' {
  declare module.exports: any;
}

declare module '@react-navigation/native/lib/module/theming/DefaultTheme' {
  declare module.exports: any;
}

declare module '@react-navigation/native/lib/module/theming/ThemeContext' {
  declare module.exports: any;
}

declare module '@react-navigation/native/lib/module/theming/ThemeProvider' {
  declare module.exports: any;
}

declare module '@react-navigation/native/lib/module/theming/useTheme' {
  declare module.exports: any;
}

declare module '@react-navigation/native/lib/module/types' {
  declare module.exports: any;
}

declare module '@react-navigation/native/lib/module/useBackButton' {
  declare module.exports: any;
}

declare module '@react-navigation/native/lib/module/useLinkBuilder' {
  declare module.exports: any;
}

declare module '@react-navigation/native/lib/module/useLinking' {
  declare module.exports: any;
}

declare module '@react-navigation/native/lib/module/useLinking.native' {
  declare module.exports: any;
}

declare module '@react-navigation/native/lib/module/useLinkProps' {
  declare module.exports: any;
}

declare module '@react-navigation/native/lib/module/useLinkTo' {
  declare module.exports: any;
}

declare module '@react-navigation/native/lib/module/useScrollToTop' {
  declare module.exports: any;
}

declare module '@react-navigation/native/lib/module/useThenable' {
  declare module.exports: any;
}

// Filename aliases
declare module '@react-navigation/native/lib/commonjs/index' {
  declare module.exports: $Exports<'@react-navigation/native/lib/commonjs'>;
}
declare module '@react-navigation/native/lib/commonjs/index.js' {
  declare module.exports: $Exports<'@react-navigation/native/lib/commonjs'>;
}
declare module '@react-navigation/native/lib/commonjs/Link.js' {
  declare module.exports: $Exports<'@react-navigation/native/lib/commonjs/Link'>;
}
declare module '@react-navigation/native/lib/commonjs/LinkingContext.js' {
  declare module.exports: $Exports<'@react-navigation/native/lib/commonjs/LinkingContext'>;
}
declare module '@react-navigation/native/lib/commonjs/NavigationContainer.js' {
  declare module.exports: $Exports<'@react-navigation/native/lib/commonjs/NavigationContainer'>;
}
declare module '@react-navigation/native/lib/commonjs/ServerContainer.js' {
  declare module.exports: $Exports<'@react-navigation/native/lib/commonjs/ServerContainer'>;
}
declare module '@react-navigation/native/lib/commonjs/ServerContext.js' {
  declare module.exports: $Exports<'@react-navigation/native/lib/commonjs/ServerContext'>;
}
declare module '@react-navigation/native/lib/commonjs/theming/DarkTheme.js' {
  declare module.exports: $Exports<'@react-navigation/native/lib/commonjs/theming/DarkTheme'>;
}
declare module '@react-navigation/native/lib/commonjs/theming/DefaultTheme.js' {
  declare module.exports: $Exports<'@react-navigation/native/lib/commonjs/theming/DefaultTheme'>;
}
declare module '@react-navigation/native/lib/commonjs/theming/ThemeContext.js' {
  declare module.exports: $Exports<'@react-navigation/native/lib/commonjs/theming/ThemeContext'>;
}
declare module '@react-navigation/native/lib/commonjs/theming/ThemeProvider.js' {
  declare module.exports: $Exports<'@react-navigation/native/lib/commonjs/theming/ThemeProvider'>;
}
declare module '@react-navigation/native/lib/commonjs/theming/useTheme.js' {
  declare module.exports: $Exports<'@react-navigation/native/lib/commonjs/theming/useTheme'>;
}
declare module '@react-navigation/native/lib/commonjs/types.js' {
  declare module.exports: $Exports<'@react-navigation/native/lib/commonjs/types'>;
}
declare module '@react-navigation/native/lib/commonjs/useBackButton.js' {
  declare module.exports: $Exports<'@react-navigation/native/lib/commonjs/useBackButton'>;
}
declare module '@react-navigation/native/lib/commonjs/useLinkBuilder.js' {
  declare module.exports: $Exports<'@react-navigation/native/lib/commonjs/useLinkBuilder'>;
}
declare module '@react-navigation/native/lib/commonjs/useLinking.js' {
  declare module.exports: $Exports<'@react-navigation/native/lib/commonjs/useLinking'>;
}
declare module '@react-navigation/native/lib/commonjs/useLinking.native.js' {
  declare module.exports: $Exports<'@react-navigation/native/lib/commonjs/useLinking.native'>;
}
declare module '@react-navigation/native/lib/commonjs/useLinkProps.js' {
  declare module.exports: $Exports<'@react-navigation/native/lib/commonjs/useLinkProps'>;
}
declare module '@react-navigation/native/lib/commonjs/useLinkTo.js' {
  declare module.exports: $Exports<'@react-navigation/native/lib/commonjs/useLinkTo'>;
}
declare module '@react-navigation/native/lib/commonjs/useScrollToTop.js' {
  declare module.exports: $Exports<'@react-navigation/native/lib/commonjs/useScrollToTop'>;
}
declare module '@react-navigation/native/lib/commonjs/useThenable.js' {
  declare module.exports: $Exports<'@react-navigation/native/lib/commonjs/useThenable'>;
}
declare module '@react-navigation/native/lib/module/index' {
  declare module.exports: $Exports<'@react-navigation/native/lib/module'>;
}
declare module '@react-navigation/native/lib/module/index.js' {
  declare module.exports: $Exports<'@react-navigation/native/lib/module'>;
}
declare module '@react-navigation/native/lib/module/Link.js' {
  declare module.exports: $Exports<'@react-navigation/native/lib/module/Link'>;
}
declare module '@react-navigation/native/lib/module/LinkingContext.js' {
  declare module.exports: $Exports<'@react-navigation/native/lib/module/LinkingContext'>;
}
declare module '@react-navigation/native/lib/module/NavigationContainer.js' {
  declare module.exports: $Exports<'@react-navigation/native/lib/module/NavigationContainer'>;
}
declare module '@react-navigation/native/lib/module/ServerContainer.js' {
  declare module.exports: $Exports<'@react-navigation/native/lib/module/ServerContainer'>;
}
declare module '@react-navigation/native/lib/module/ServerContext.js' {
  declare module.exports: $Exports<'@react-navigation/native/lib/module/ServerContext'>;
}
declare module '@react-navigation/native/lib/module/theming/DarkTheme.js' {
  declare module.exports: $Exports<'@react-navigation/native/lib/module/theming/DarkTheme'>;
}
declare module '@react-navigation/native/lib/module/theming/DefaultTheme.js' {
  declare module.exports: $Exports<'@react-navigation/native/lib/module/theming/DefaultTheme'>;
}
declare module '@react-navigation/native/lib/module/theming/ThemeContext.js' {
  declare module.exports: $Exports<'@react-navigation/native/lib/module/theming/ThemeContext'>;
}
declare module '@react-navigation/native/lib/module/theming/ThemeProvider.js' {
  declare module.exports: $Exports<'@react-navigation/native/lib/module/theming/ThemeProvider'>;
}
declare module '@react-navigation/native/lib/module/theming/useTheme.js' {
  declare module.exports: $Exports<'@react-navigation/native/lib/module/theming/useTheme'>;
}
declare module '@react-navigation/native/lib/module/types.js' {
  declare module.exports: $Exports<'@react-navigation/native/lib/module/types'>;
}
declare module '@react-navigation/native/lib/module/useBackButton.js' {
  declare module.exports: $Exports<'@react-navigation/native/lib/module/useBackButton'>;
}
declare module '@react-navigation/native/lib/module/useLinkBuilder.js' {
  declare module.exports: $Exports<'@react-navigation/native/lib/module/useLinkBuilder'>;
}
declare module '@react-navigation/native/lib/module/useLinking.js' {
  declare module.exports: $Exports<'@react-navigation/native/lib/module/useLinking'>;
}
declare module '@react-navigation/native/lib/module/useLinking.native.js' {
  declare module.exports: $Exports<'@react-navigation/native/lib/module/useLinking.native'>;
}
declare module '@react-navigation/native/lib/module/useLinkProps.js' {
  declare module.exports: $Exports<'@react-navigation/native/lib/module/useLinkProps'>;
}
declare module '@react-navigation/native/lib/module/useLinkTo.js' {
  declare module.exports: $Exports<'@react-navigation/native/lib/module/useLinkTo'>;
}
declare module '@react-navigation/native/lib/module/useScrollToTop.js' {
  declare module.exports: $Exports<'@react-navigation/native/lib/module/useScrollToTop'>;
}
declare module '@react-navigation/native/lib/module/useThenable.js' {
  declare module.exports: $Exports<'@react-navigation/native/lib/module/useThenable'>;
}
