// flow-typed signature: 42da4377533d9a8d06edd609bb9b4f43
// flow-typed version: <<STUB>>/@bam.tech/react-native-make_v^3.0.0/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@bam.tech/react-native-make'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@bam.tech/react-native-make' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@bam.tech/react-native-make/dist/logo' {
  declare module.exports: any;
}

declare module '@bam.tech/react-native-make/dist/modules/config' {
  declare module.exports: any;
}

declare module '@bam.tech/react-native-make/dist/modules' {
  declare module.exports: any;
}

declare module '@bam.tech/react-native-make/dist/modules/setIcon/android/config' {
  declare module.exports: any;
}

declare module '@bam.tech/react-native-make/dist/modules/setIcon/android/service' {
  declare module.exports: any;
}

declare module '@bam.tech/react-native-make/dist/modules/setIcon/ios/config' {
  declare module.exports: any;
}

declare module '@bam.tech/react-native-make/dist/modules/setIcon/ios/service' {
  declare module.exports: any;
}

declare module '@bam.tech/react-native-make/dist/modules/setIcon/setIcon.command' {
  declare module.exports: any;
}

declare module '@bam.tech/react-native-make/dist/modules/setIcon/setIcon.task' {
  declare module.exports: any;
}

declare module '@bam.tech/react-native-make/dist/modules/setSplashScreen/android/config' {
  declare module.exports: any;
}

declare module '@bam.tech/react-native-make/dist/modules/setSplashScreen/android/service' {
  declare module.exports: any;
}

declare module '@bam.tech/react-native-make/dist/modules/setSplashScreen/ios/config' {
  declare module.exports: any;
}

declare module '@bam.tech/react-native-make/dist/modules/setSplashScreen/ios/service' {
  declare module.exports: any;
}

declare module '@bam.tech/react-native-make/dist/modules/setSplashScreen/setSplashScreen.command' {
  declare module.exports: any;
}

declare module '@bam.tech/react-native-make/dist/modules/setSplashScreen/setSplashScreen.task' {
  declare module.exports: any;
}

declare module '@bam.tech/react-native-make/dist/rn-plugin.config' {
  declare module.exports: any;
}

declare module '@bam.tech/react-native-make/dist/services/analytics' {
  declare module.exports: any;
}

declare module '@bam.tech/react-native-make/dist/services/color.processing' {
  declare module.exports: any;
}

declare module '@bam.tech/react-native-make/dist/services/file.processing' {
  declare module.exports: any;
}

declare module '@bam.tech/react-native-make/dist/services/image.processing' {
  declare module.exports: any;
}

declare module '@bam.tech/react-native-make/dist/services/ios/service' {
  declare module.exports: any;
}

declare module '@bam.tech/react-native-make/dist/services/type' {
  declare module.exports: any;
}

declare module '@bam.tech/react-native-make/dist/utils' {
  declare module.exports: any;
}

declare module '@bam.tech/react-native-make/react-native.config' {
  declare module.exports: any;
}

// Filename aliases
declare module '@bam.tech/react-native-make/dist/logo.js' {
  declare module.exports: $Exports<'@bam.tech/react-native-make/dist/logo'>;
}
declare module '@bam.tech/react-native-make/dist/modules/config.js' {
  declare module.exports: $Exports<'@bam.tech/react-native-make/dist/modules/config'>;
}
declare module '@bam.tech/react-native-make/dist/modules/index' {
  declare module.exports: $Exports<'@bam.tech/react-native-make/dist/modules'>;
}
declare module '@bam.tech/react-native-make/dist/modules/index.js' {
  declare module.exports: $Exports<'@bam.tech/react-native-make/dist/modules'>;
}
declare module '@bam.tech/react-native-make/dist/modules/setIcon/android/config.js' {
  declare module.exports: $Exports<'@bam.tech/react-native-make/dist/modules/setIcon/android/config'>;
}
declare module '@bam.tech/react-native-make/dist/modules/setIcon/android/service.js' {
  declare module.exports: $Exports<'@bam.tech/react-native-make/dist/modules/setIcon/android/service'>;
}
declare module '@bam.tech/react-native-make/dist/modules/setIcon/ios/config.js' {
  declare module.exports: $Exports<'@bam.tech/react-native-make/dist/modules/setIcon/ios/config'>;
}
declare module '@bam.tech/react-native-make/dist/modules/setIcon/ios/service.js' {
  declare module.exports: $Exports<'@bam.tech/react-native-make/dist/modules/setIcon/ios/service'>;
}
declare module '@bam.tech/react-native-make/dist/modules/setIcon/setIcon.command.js' {
  declare module.exports: $Exports<'@bam.tech/react-native-make/dist/modules/setIcon/setIcon.command'>;
}
declare module '@bam.tech/react-native-make/dist/modules/setIcon/setIcon.task.js' {
  declare module.exports: $Exports<'@bam.tech/react-native-make/dist/modules/setIcon/setIcon.task'>;
}
declare module '@bam.tech/react-native-make/dist/modules/setSplashScreen/android/config.js' {
  declare module.exports: $Exports<'@bam.tech/react-native-make/dist/modules/setSplashScreen/android/config'>;
}
declare module '@bam.tech/react-native-make/dist/modules/setSplashScreen/android/service.js' {
  declare module.exports: $Exports<'@bam.tech/react-native-make/dist/modules/setSplashScreen/android/service'>;
}
declare module '@bam.tech/react-native-make/dist/modules/setSplashScreen/ios/config.js' {
  declare module.exports: $Exports<'@bam.tech/react-native-make/dist/modules/setSplashScreen/ios/config'>;
}
declare module '@bam.tech/react-native-make/dist/modules/setSplashScreen/ios/service.js' {
  declare module.exports: $Exports<'@bam.tech/react-native-make/dist/modules/setSplashScreen/ios/service'>;
}
declare module '@bam.tech/react-native-make/dist/modules/setSplashScreen/setSplashScreen.command.js' {
  declare module.exports: $Exports<'@bam.tech/react-native-make/dist/modules/setSplashScreen/setSplashScreen.command'>;
}
declare module '@bam.tech/react-native-make/dist/modules/setSplashScreen/setSplashScreen.task.js' {
  declare module.exports: $Exports<'@bam.tech/react-native-make/dist/modules/setSplashScreen/setSplashScreen.task'>;
}
declare module '@bam.tech/react-native-make/dist/rn-plugin.config.js' {
  declare module.exports: $Exports<'@bam.tech/react-native-make/dist/rn-plugin.config'>;
}
declare module '@bam.tech/react-native-make/dist/services/analytics.js' {
  declare module.exports: $Exports<'@bam.tech/react-native-make/dist/services/analytics'>;
}
declare module '@bam.tech/react-native-make/dist/services/color.processing.js' {
  declare module.exports: $Exports<'@bam.tech/react-native-make/dist/services/color.processing'>;
}
declare module '@bam.tech/react-native-make/dist/services/file.processing.js' {
  declare module.exports: $Exports<'@bam.tech/react-native-make/dist/services/file.processing'>;
}
declare module '@bam.tech/react-native-make/dist/services/image.processing.js' {
  declare module.exports: $Exports<'@bam.tech/react-native-make/dist/services/image.processing'>;
}
declare module '@bam.tech/react-native-make/dist/services/ios/service.js' {
  declare module.exports: $Exports<'@bam.tech/react-native-make/dist/services/ios/service'>;
}
declare module '@bam.tech/react-native-make/dist/services/type.js' {
  declare module.exports: $Exports<'@bam.tech/react-native-make/dist/services/type'>;
}
declare module '@bam.tech/react-native-make/dist/utils.js' {
  declare module.exports: $Exports<'@bam.tech/react-native-make/dist/utils'>;
}
declare module '@bam.tech/react-native-make/react-native.config.js' {
  declare module.exports: $Exports<'@bam.tech/react-native-make/react-native.config'>;
}
