name: Testing the JS level code

on: pull_request

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          yarn
      - name: Run lint checks
        run: |
          yarn lint
      - name: Test type checks
        run: |
          yarn flow
      - name: Unit test files
        run: |
          yarn test